name: Build and deploy Vite app to Azure Web App - sawmp

on:
  push:
    branches:
      - vite-typescript-migration
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          # ⚠️ ONLY frontend-safe env vars go here
          # Do NOT add EVENTHUB_CONNECTION_STR, AZURE_SUBSCRIPTION_ID, etc. (keep them in Azure App Settings)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist  # Vite build output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sawmp'
          slot-name: 'Production'
          package: ./dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58F1F06CE7814252B9AE0728647A8454 }}
